modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/zack-zzq/Create-Originium-Industry/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://github.com/zack-zzq/Create-Originium-Industry"
    logoFile="logo.png"
    credits="Depends on Create. Gameplay inspired by Arknights; original assets only."
    authors="${mod_authors}"
    description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
